<?php $this->headTitle('Portfolio') ?>

<div class="row">
    <?php foreach($this->models as $model):?>
    <div class="col-sm-3">
        <div class="thumbnail">
            <img src="<?=$this->basePath('userfiles/thumbnails/' . $this->escapeHtml($model->getImage()));?>">
            <div class="caption">
                <h3>Thumbnail label</h3>
                <p><?=$this->escapeHtml($model->getDescription());?></p>
                <?php if ($model->getLink()):?>
                <p><a href="<?=$this->escapeHtml($model->getLink());?>" class="btn btn-primary" role="button">Button</a></p>
                <?php endif;?>
            </div>
        </div>
    </div>
    <?php endforeach;?>
</div>