<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoPortfolio\Module'                   => __DIR__ . '/Module.php',
    'UthandoPortfolio\Form\Portfolio'           => __DIR__ . '/src/UthandoPortfolio/Form/Portfolio.php',
    'UthandoPortfolio\Hydrator\Portfolio'       => __DIR__ . '/src/UthandoPortfolio/Hydrator/Portfolio.php',
    'UthandoPortfolio\InputFilter\Portfolio'    => __DIR__ . '/src/UthandoPortfolio/InputFilter/Portfolio.php',
    'UthandoPortfolio\Mapper\Portfolio'         => __DIR__ . '/src/UthandoPortfolio/Mapper/Portfolio.php',
    'UthandoPortfolio\Model\Portfolio'          => __DIR__ . '/src/UthandoPortfolio/Model/Portfolio.php',
    'UthandoPortfolio\Mvc\Controller\Admin'     => __DIR__ . '/src/UthandoPortfolio/Mvc/Controller/Admin.php',
    'UthandoPortfolio\Mvc\Controller\Portfolio' => __DIR__ . '/src/UthandoPortfolio/Mvc/Controller/Portfolio.php',
    'UthandoPortfolio\Service\Portfolio'        => __DIR__ . '/src/UthandoPortfolio/Service/Portfolio.php',
);
