<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-portfolio/admin/add'      => __DIR__ . '/view/uthando-portfolio/admin/add.phtml',
    'uthando-portfolio/admin/edit'     => __DIR__ . '/view/uthando-portfolio/admin/edit.phtml',
    'uthando-portfolio/admin/index'    => __DIR__ . '/view/uthando-portfolio/admin/index.phtml',
    'uthando-portfolio/admin/list'     => __DIR__ . '/view/uthando-portfolio/admin/list.phtml',
    'uthando-portfolio/portfolio/view' => __DIR__ . '/view/uthando-portfolio/portfolio/view.phtml',
);
