<?php if (count($this->models) > 0): ?>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="portfolioTagId">Tag Id</th>
                <th data-field="name">Name</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoPortfolio\Model\TagModel */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getPortfolioTagId()); ?></td>
                    <td><?=$this->escapeHtml($row->getName()); ?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'portfolioTagId',
                            'id'		=> $row->getPortfolioTagId(),
                            'tableName'	=> 'portfolioTag',
                            'route'		=> 'admin/portfolio/tag/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/portfolio/tag/page']
    ); ?>

<?php else: ?>
    <h4>There are no Tags yet.</h4>
<?php endif; ?>