<?php $this->headTitle('Add Portfolio Item') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Portfolio Item');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-portfolio" data-toggle="tooltip" title="Save" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/portfolio');?>" type="submit" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-portfolio',
    'action' => $this->url('admin/portfolio/edit', [
        'action' => 'add',
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Add Item');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>

<?=$this->fileManager()->uploadButton('portfolio-image', 'portfolio-image-button');?>
