<?php if (count($this->models) > 0): ?>

    <div class="table-responsive">
        <table class="table table-hover table-bordered table-condensed sortable-table">
            <thead>
            <tr>
                <th data-field="portfolioId"><?=$this->translate('Portfolio Id');?></th>
                <th data-field="label"><?=$this->translate('Label');?></th>
                <th data-field="image"><?=$this->translate('Image');?></th>
                <th data-field="link"><?=$this->translate('Link');?></th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody>
            <?php /* @var $row \UthandoPortfolio\Model\PortfolioModel */ ?>
            <?php foreach ($this->models as $row): ?>
                <tr>
                    <td><?= $this->escapeHtml($row->getPortfolioId()); ?></td>
                    <td><?= $this->escapeHtml($row->getLabel()); ?></td>
                    <td><?= $this->escapeHtml($row->getImage()); ?></td>
                    <td><?= $this->escapeHtml($row->getLink()); ?></td>
                    <td>
                        <?= $this->partial('uthando-admin/partial/edit-actions', [
                            'pk' => 'portfolioId',
                            'id' => $row->getPortfolioId(),
                            'tableName' => 'portfolio',
                            'route' => 'admin/portfolio/edit',
                        ]); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?= $this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/user/page']
    ); ?>

<?php else: ?>
    <h4><?=$this->translate('No items where returned by search.');?></h4>
<?php endif; ?>

